### ISSUE TITLE
Assign funtionality dont show all users in list

### ISSUE THREAD

**Issue by KazimGok** [rappen/BulkDataUpdater#65] opened 2020-07-15 11:31 UTC
Hi Jonas,

I am not able to select all users. The user list didnt show all the users. 

Any idea?

**Comment by rappen** [comment] 2020-07-15 14:17
Can you share the query you are using? Easiest way is to click the **Edit FetchXML** button.

![image](https://user-images.githubusercontent.com/2572253/87556186-a56db780-c6b6-11ea-8c2a-a070b3c18591.png)

**Comment by rappen** [comment] 2020-09-29 06:57
Closing since there was no more feedback. Feel free to reopen if necessary.

**Comment by leeh795** [comment] 2021-07-29 04:18
I'm seeing the same issue as the original poster. The problem isn't the FetchXML query but when utilizing the "Assign" feature for the records.

When using the "Assign" feature there are two dropdowns which will show a list of Users and Teams but the query behind this dropdown seems to be limited. 

For D365 environments with over 5,000+ users/teams it becomes a problem because the list of users is limited to a certain amount and I couldn't find a name which starts with "Z" for example.

Would it be possible to also just support entering Guids? thanks!

**Closed** 2022-04-26 17:36 UTC
